### ISSUE TITLE
Does this package support react-quill v2.0.0 ?

### ISSUE THREAD

**Issue by funcpp** [seehar/quill-better-table-plus#1]
I got the error below

Cannot read properties of undefined (reading 'pop')
TypeError: Cannot read properties of undefined (reading 'pop')
    at new quill_better_table_plus_BetterTable (http://localhost:3000/static/js/bundle.js:55177:63)
    at SnowTheme.addModule (http://localhost:3000/static/js/bundle.js:71888:34)
    at SnowTheme.addModule (http://localhost:3000/static/js/bundle.js:72647:127)
    at http://localhost:3000/static/js/bundle.js:71880:23
    at Array.forEach (<anonymous>)
    at SnowTheme.init (http://localhost:3000/static/js/bundle.js:71878:47)
    at new Quill (http://localhost:3000/static/js/bundle.js:66545:22)
    at ReactQuill.createEditor (http://localhost:3000/static/js/bundle.js:114528:18)
    at ReactQuill.instantiateEditor (http://localhost:3000/static/js/bundle.js:114494:26)
    at ReactQuill.componentDidMount (http://localhost:3000/static/js/bundle.js:114451:10)

**Comment by seehar** [comment]
Yes, forked on quill-better-table, only a few changes so far, I've got it working well in my vue project, haven't tried it in my react project.

**Comment by PriyomSaha** [comment]
I am getting kind of same error in react
Cannot read properties of undefined (reading 'pop')
TypeError: Cannot read properties of undefined (reading 'pop')
    at new quill_better_table_plus_BetterTable (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:3237:63)
    at SnowTheme.addModule (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:10087:34)
    at SnowTheme.addModule (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:10846:127)
    at http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:10079:23
    at Array.forEach (<anonymous>)
    at SnowTheme.init (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:10077:47)
    at new Quill (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:4744:22)
    at ReactQuill.createEditor (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:16295:18)
    at ReactQuill.instantiateEditor (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:16261:26)
    at ReactQuill.componentDidMount (http://localhost:3000/static/js/vendors-node_modules_mui_system_esm_Box_Box_js-node_modules_quill-better-table-plus_dist_quil-553303.chunk.js:16218:10)

**Comment by enzedonline** [comment]
I'm using Quill 2.02, pure JS, with the 0.1.6 cdn for better-table-plus:
https://unpkg.com/quill-better-table-plus@0.1.6/dist/quill-better-table-plus.min.js
https://unpkg.com/quill-better-table-plus@0.1.6/dist/quill-better-table-plus.css

Everything works fine except the keyboard bindings :
```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at keyboard.ts:260:32
    at Array.some (<anonymous>)
    at HTMLDivElement.<anonymous> (keyboard.ts:218:33)
```

**Comment by HaHa1698** [comment]
Does it has any update?

**Comment by panmona** [comment]
Did someone get this plug-in to work with QuillV2 (non-beta)?
