### ISSUE TITLE
keyboard bindings error

### ISSUE THREAD

**Issue by enzedonline** [seehar/quill-better-table-plus#6]
I'm using 0.1.6 on pure JS - the keyboard bindings throw an error each key press:

Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at keyboard.ts:260:32
    at Array.some (<anonymous>)
    at HTMLDivElement.<anonymous> (keyboard.ts:218:33)

This is a hangover from the same error on quill-better-table. Is there a known solution to this?

**Comment by enzedonline** [comment]
Turned out to be a config error on my part - perils of passing config from python ...
